name: node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  #<--start of build encapsulation
      - name: checkout
        uses: actions/checkout@v4
      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: install npm
        run: npm install
      - name: install dependencies
        run: npm ci
      - name: npm build
        run: npm run build
      - name: Deploy
        if: github.ref == 'refs/heads/test' && github.event_name == 'push'
        run: |
          npm run deploy
          echo "deploy the file"
        
